name: Deploying to development

on: [workflow_dispatch]

jobs:
    dockerify:
        runs-on: ubuntu-latest
        if: ${{ github.ref == 'refs/heads/dev' }}

        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push to docker hub
              uses: docker/build-push-action@v2
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/sellify_backend_dev:latest

    deploy:
        runs-on: ubuntu-latest
        needs: [dockerify]
        if: ${{ github.ref == 'refs/heads/dev' }}

        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: Generate deployment package
              run: |
                  zip -r deploy.zip . -x '*.git*' -x 'tests/*' -x 'node_modules/*' -x '.github/*' -x 'jest.config.js' -x 'Dockerfile.dev'

            - name: Deploy to EB
              uses: einaregilsson/beanstalk-deploy@v20
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  application_name: sellify_dev
                  environment_name: Sellifydev-env
                  version_label: sellify_dev_deploy_pipeline_${{ github.sha }}_version
                  region: ap-south-1
                  deployment_package: deploy.zip
                  wait_for_environment_recovery: 120
