name: Sellify Backend production CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_test:

    runs-on: ubuntu-latest
    env:
      JWT_SECRET: secret
    strategy:
      matrix:
        node_version: [16.10.x] 
        mongodb-version: ['5.0']

    steps:
    - uses: actions/checkout@v3
    
    - name: setup node
      uses: actions/setup-node@master
      with:
        node-version: ${{matrix.node_version}}
       
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}   
        
    - name: install app dependencies
      run: npm install
      
    - name: test app
      run : npm test

  dockerify:

    runs-on: ubuntu-latest
    needs: [build_test]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sellify_backend:latest

  deploy: 
    runs-on: ubuntu-latest
    needs: [build_test, dockerify]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3    

      - name: Generate deployment package
        run: |
          mkdir temp
          cp -r src temp
          cp package.json temp
          cp package-lock.json temp
          cp Dockerfile temp
          zip -r deploy.zip temp

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: sellify_backend_dev
          environment_name: Sellifybackenddev-env
          version_label: version-2
          region: us-east-1
          deployment_package: deploy.zip              

    
    
