name: Sellify Backend production CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16.10.x] 
        mongodb-version: ['4.2', '4.4', '5.0']

    steps:
    - uses: actions/checkout@v3
    
    - name: setup node
      uses: actions/setup-node@master
      with:
        node-version: ${{matrix.node_version}}
       
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}   
        
    - name: install app dependencies
      run: npm install
      
    - name: test app
      run : npm test
    
    
